FROM building5/dumb-init:1.2.1 as init

# The build image
FROM node:latest AS build
RUN apt-get update && apt-get install -y --no-install-recommends dumb-init
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN --mount=type=secret,mode=0644,id=npmrc,target=/usr/src/app/.npmrc npm install --only=production
 
# The production image
FROM node:16.17.0-alpine

ENV NODE_ENV production
#COPY --from=build /usr/bin/dumb-init /usr/local/bin/dumb-init
COPY --from=init /dumb-init /usr/local/bin/
# added this for alpine based image
#RUN apk add dumb-init 
USER node
WORKDIR /usr/src/app
COPY --chown=node:node --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY --chown=node:node . /usr/src/app
#EXPOSE 8081
#CMD ["ls", "-l", "/usr/local/bin/"]
CMD ["dumb-init", "node", "server.js"]